// angular/src/app/components/product-overview/product-overview.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { Product } from 'src/app/interfaces/product';
import { DataApiService } from 'src/app/services/data-api.service';

@Component({
  selector: 'app-product-overview',
  templateUrl: './product-overview.component.html',
  styleUrls: ['./product-overview.component.scss']
})
export class ProductOverviewComponent implements OnInit, OnDestroy {

  product?: Product;
  productSubscription?: Subscription;

  ratings: number[] = [1,2,3,4,5];

  selectedImageId?: number;

  constructor(private dataApiService:DataApiService) { }

  ngOnInit(): void {
    this.productSubscription = this.dataApiService.productForOverViewSubject.subscribe(productForOverView =>
      {
        this.product = productForOverView;
        this.selectedImageId = ( this.product && this.product.images && this.product.images.length > 0 ) ?
            this.product.images[0].id : undefined;
      })

      this.dataApiService.getProductForOverView();
  }

  ngOnDestroy(): void {
    this.productSubscription?.unsubscribe();
  }

  onSelectedImage( selectedImageId: number) :void{
    this.selectedImageId = selectedImageId;
  }

}

<app-header-main></app-header-main>
<ng-template [ngIf]="product">
  <div class="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
    <div class="lg:grid lg:grid-cols-2 lg:gap-x-8 lg:items-start">
      <!-- Image galery-->
      <div class="flex flex-col-reverse">
        <!-- Image selector-->
        <div class="hidden mt-6 w-full max-w-2xl mx-auto sm:block lg:max-w-none">
          <div class="grid grid-cols-4 gap-6">
              <ng-container *ngFor="let image of product.images">
                <button
                    class="relative aspect-w-1 aspect-h-1 bg-white rounded-md flex items-center justify-center text-sm font-medium uppercase text-gray-900 cursor-pointer hover:bg-gray-50 focus:outline-none focus:ring focus:ring-offset-4 focus:ring-opacity-50"
                    (click)="onSelectedImage(image.id)" type="button"
                  >
                  <span class="sr-only">{{image.name}}</span>
                        <span class="absolute inset-0 rounded-md overflow-hidden">
                          <TwicImg [src]="image.src"></TwicImg>
                        </span>
                        <span class="absolute inset-0 rounded-md ring-2 ring-offset-2 pointer-events-none"
                              [ngClass]="{
                                'ring-indigo-500' : image.id === selectedImageId,
                                'ring-transparent' : image.id !== selectedImageId
                                }"
                                aria-hidden="true">
                        </span>
                </button>
              </ng-container>
          </div>
        </div>
        <!-- Image selector end -->
        <div class="w-full aspect-w-1 aspect-h-1">
          <ng-container *ngFor="let image of product.images">
            <div *ngIf="image.id === selectedImageId">
              <TwicImg [src]="image.src" [alt]="image.alt"></TwicImg>
            </div>
          </ng-container>
        </div>
      </div>

      <!-- Image galery end -->
      <!-- Product info -->
      <div class="mt-10 px-4 sm:px-0 sm:mt-16 lg:mt-0">
        <h1 class="text-3xl font-extrabold tracking-tight text-gray-900">
          {{product.name}}
        </h1>
        <div class="mt-3">
          <h2 class="sr-only">Product information</h2>
          <p class="text-3xl text-gray-900">{{product.price}}</p>
        </div>
        <!-- Reviews -->
        <div class="mt-3">
          <h3 class="sr-only">Reviews</h3>
          <div class="flew items-center">
            <div class="flex items-center">
                <ng-container *ngFor="let rating of ratings">
                  <app-star [rating]="product.rating" [value]="rating"></app-star>
                </ng-container>
            </div>
          </div>
          <p class="sr-only">{{product.rating}} out of {{ratings.length}} stars</p>
        </div>
        <!-- Reviews end-->
        <!-- Description-->
        <div class="mt-6">
          <h3 class="sr-only">Description</h3>
          <div class="text-base text-gray-700 space-y-6" [innerHTML]="product.description"></div>
        </div>
        <!-- Description end-->
      </div>
    </div>
  </div>
</ng-template>

// vue3/src/components/ProductOverview.vue
<template>
  <div class="bg-white">
    <div class="flex justify-center text-white bg-twicpics">
      <h1 class="flex items-center">
        <img
          class="h-8 object-contain"
          src="../assets/twicpics-logo.svg"
          alt="TwicPics logo"
        />
        <span class="ml-3 mr-1">x</span>
        <img
          class="h-12 object-contain"
          src="../assets/vue-logo.png"
          alt="Vue.JS logo"
        />
      </h1>
    </div>
    <div
      class="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8"
    >
      <div class="lg:grid lg:grid-cols-2 lg:gap-x-8 lg:items-start">
        <!-- Image gallery -->
        <TabGroup as="div" class="flex flex-col-reverse">
          <!-- Image selector -->
          <div
            class="hidden mt-6 w-full max-w-2xl mx-auto sm:block lg:max-w-none"
          >
            <TabList class="grid grid-cols-4 gap-6">
              <Tab
                v-for="image in product.images"
                :key="image.id"
                class="relative aspect-w-1 aspect-h-1 bg-white rounded-md flex items-center justify-center text-sm font-medium uppercase text-gray-900 cursor-pointer hover:bg-gray-50 focus:outline-none focus:ring focus:ring-offset-4 focus:ring-opacity-50"
                v-slot="{ selected }"
              >
                <span class="sr-only">
                  {{ image.name }}
                </span>
                <span class="absolute inset-0 rounded-md overflow-hidden">
                  <TwicImg :src="image.src" alt="" />
                </span>
                <span
                  :class="[
                    selected ? 'ring-indigo-500' : 'ring-transparent',
                    'absolute inset-0 rounded-md ring-2 ring-offset-2 pointer-events-none'
                  ]"
                  aria-hidden="true"
                />
              </Tab>
            </TabList>
          </div>

          <TabPanels class="w-full aspect-w-1 aspect-h-1">
            <TabPanel v-for="image in product.images" :key="image.id">
              <TwicImg :src="image.src" :alt="image.alt" />
            </TabPanel>
          </TabPanels>
        </TabGroup>

        <!-- Product info -->
        <div class="mt-10 px-4 sm:px-0 sm:mt-16 lg:mt-0">
          <h1 class="text-3xl font-extrabold tracking-tight text-gray-900">
            {{ product.name }}
          </h1>

          <div class="mt-3">
            <h2 class="sr-only">Product information</h2>
            <p class="text-3xl text-gray-900">{{ product.price }}</p>
          </div>

          <!-- Reviews -->
          <div class="mt-3">
            <h3 class="sr-only">Reviews</h3>
            <div class="flex items-center">
              <div class="flex items-center">
                <StarIcon
                  v-for="rating in [0, 1, 2, 3, 4]"
                  :key="rating"
                  :class="[
                    product.rating > rating
                      ? 'text-indigo-500'
                      : 'text-gray-300',
                    'h-5 w-5 flex-shrink-0'
                  ]"
                  aria-hidden="true"
                />
              </div>
              <p class="sr-only">{{ product.rating }} out of 5 stars</p>
            </div>
          </div>

          <div class="mt-6">
            <h3 class="sr-only">Description</h3>

            <div
              class="text-base text-gray-700 space-y-6"
              v-html="product.description"
            />
          </div>

          <form class="mt-6">
            <!-- Colors -->
            <div>
              <h3 class="text-sm text-gray-600">Color</h3>

              <RadioGroup v-model="selectedColor" class="mt-2">
                <RadioGroupLabel class="sr-only">
                  Choose a color
                </RadioGroupLabel>
                <div class="flex items-center space-x-3">
                  <RadioGroupOption
                    as="template"
                    v-for="color in product.colors"
                    :key="color.name"
                    :value="color"
                    v-slot="{ active, checked }"
                  >
                    <div
                      :class="[
                        color.selectedColor,
                        active && checked ? 'ring ring-offset-1' : '',
                        !active && checked ? 'ring-2' : '',
                        '-m-0.5 relative p-0.5 rounded-full flex items-center justify-center cursor-pointer focus:outline-none'
                      ]"
                    >
                      <RadioGroupLabel as="p" class="sr-only">
                        {{ color.name }}
                      </RadioGroupLabel>
                      <span
                        aria-hidden="true"
                        :class="[
                          color.bgColor,
                          'h-8 w-8 border border-black border-opacity-10 rounded-full'
                        ]"
                      />
                    </div>
                  </RadioGroupOption>
                </div>
              </RadioGroup>
            </div>

            <div class="mt-10 flex sm:flex-col1">
              <button
                type="submit"
                class="max-w-xs flex-1 bg-indigo-600 border border-transparent rounded-md py-3 px-8 flex items-center justify-center text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-50 focus:ring-indigo-500 sm:w-full"
              >
                Add to bag
              </button>

              <button
                type="button"
                class="ml-4 py-3 px-3 rounded-md flex items-center justify-center text-gray-400 hover:bg-gray-100 hover:text-gray-500"
              >
                <HeartIcon class="h-6 w-6 flex-shrink-0" aria-hidden="true" />
                <span class="sr-only">Add to favorites</span>
              </button>
            </div>
          </form>

          <section aria-labelledby="details-heading" class="mt-12">
            <h2 id="details-heading" class="sr-only">Additional details</h2>

            <div class="border-t divide-y divide-gray-200">
              <Disclosure
                as="div"
                v-for="detail in product.details"
                :key="detail.name"
                v-slot="{ open }"
              >
                <h3>
                  <DisclosureButton
                    class="group relative w-full py-6 flex justify-between items-center text-left"
                  >
                    <span
                      :class="[
                        open ? 'text-indigo-600' : 'text-gray-900',
                        'text-sm font-medium'
                      ]"
                    >
                      {{ detail.name }}
                    </span>
                    <span class="ml-6 flex items-center">
                      <PlusSmIcon
                        v-if="!open"
                        class="block h-6 w-6 text-gray-400 group-hover:text-gray-500"
                        aria-hidden="true"
                      />
                      <MinusSmIcon
                        v-else
                        class="block h-6 w-6 text-indigo-400 group-hover:text-indigo-500"
                        aria-hidden="true"
                      />
                    </span>
                  </DisclosureButton>
                </h3>
                <DisclosurePanel as="div" class="pb-6 prose prose-sm">
                  <ul role="list">
                    <li v-for="item in detail.items" :key="item">{{ item }}</li>
                  </ul>
                </DisclosurePanel>
              </Disclosure>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref } from "vue";
import {
  Disclosure,
  DisclosureButton,
  DisclosurePanel,
  RadioGroup,
  RadioGroupLabel,
  RadioGroupOption,
  Tab,
  TabGroup,
  TabList,
  TabPanel,
  TabPanels
} from "@headlessui/vue";
import { StarIcon } from "@heroicons/vue/solid";
import { HeartIcon, MinusSmIcon, PlusSmIcon } from "@heroicons/vue/outline";

const product = {
  name: "Zip Tote Basket",
  price: "$140",
  rating: 4,
  images: [
    {
      id: 1,
      name: "Angled view",
      src: "https://assets.twicpics.com/demo/fake-websites/product-overview/product-page-03-product-01.jpeg",
      alt: "Angled front view with bag zipped and handles upright.",
    },
    {
      id: 2,
      name: "Angled view",
      src: "https://assets.twicpics.com/demo/fake-websites/product-overview/product-page-03-product-02.jpeg",
      alt: "Angled front view with bag zipped and handles upright.",
    },
    {
      id: 3,
      name: "Angled view",
      src: "https://assets.twicpics.com/demo/fake-websites/product-overview/product-page-03-product-03.jpeg",
      alt: "Angled front view with bag zipped and handles upright.",
    },
    {
      id: 4,
      name: "Angled view",
      src: "https://assets.twicpics.com/demo/fake-websites/product-overview/product-page-03-product-04.jpeg",
      alt: "Angled front view with bag zipped and handles upright.",
    },
  ],
  colors: [
    {
      name: "Washed Black",
      bgColor: "bg-gray-700",
      selectedColor: "ring-gray-700"
    },
    { name: "White", bgColor: "bg-white", selectedColor: "ring-gray-400" },
    {
      name: "Washed Gray",
      bgColor: "bg-gray-500",
      selectedColor: "ring-gray-500"
    }
  ],
  description: `
    <p>The Zip Tote Basket is the perfect midpoint between shopping tote and comfy backpack. With convertible straps, you can hand carry, should sling, or backpack this convenient and spacious bag. The zip top and durable canvas construction keeps your goods protected for all-day use.</p>
  `,
  details: [
    {
      name: "Features",
      items: [
        "Multiple strap configurations",
        "Spacious interior with top zip",
        "Leather handle and tabs",
        "Interior dividers",
        "Stainless strap loops",
        "Double stitched construction",
        "Water-resistant"
      ]
    }
    // More sections...
  ]
};

export default {
  components: {
    Disclosure,
    DisclosureButton,
    DisclosurePanel,
    RadioGroup,
    RadioGroupLabel,
    RadioGroupOption,
    Tab,
    TabGroup,
    TabList,
    TabPanel,
    TabPanels,
    HeartIcon,
    MinusSmIcon,
    PlusSmIcon,
    StarIcon,
  },
  setup() {
    const selectedColor = ref(product.colors[0]);

    return {
      product,
      selectedColor
    };
  }
};
</script>
